### PR TITLE
Peer and Super Peer, and some shared models

### PR DESCRIPTION
**Pull request by Victoriatheeast**
Still working on it.

### CODE REVIEW

**Comment by meyermt** [comment]
Victoria, can you look into why there was 'com.vam' added in so many places in the project in your commit? At first I thought it could be from IntelliJ's Javadoc function, but I'm not sure that makes sense. It looks like even the README was updated?

Also, are you using `gradlew` when building and not `gradle`?

**Comment by Victoriatheeast** [comment]
I think 'com.vam' was for importing the models from the Shared Module. 
Maybe you are right I rebuilt it using Gradle. Anyway, I re-imported the project in the master branch and then rebuilt it.

**Comment by meyermt** [comment]
Virginia, can you undo those com.vam changes and then push up again? It looks like you've made changes to the Stock class. I'm not sure if they are on purpose or needed, but either way you will need to resolve the errors.

Also, please do a `git pull` locally to pull in the changes I just merged into the master branch.

**Comment by Victoriatheeast** [comment]
We only have one Stock class. I just add more variables to it. I will git pull the changes and adds my code and then push it. There's too much to do. My peer class seems to have around 400 lines of code.

**Comment by meyermt** [comment]
Yep there is too much to do. So when you do the pull I think it will ask
you to merge. Just keep your changes to the Stock class that you want. Also
I will have a couple hours to work on this tonight so let me know when you
have a working peer and I can start to help. I could build the backend
SQLite database for your peers. Would that help?

**Comment by Victoriatheeast** [comment]
Is it easier to retrieve data from the sqlite database or just a hashmap?

**Comment by meyermt** [comment]
Oh that's right, you were mentioning iterating through a map right? Forgot
about that. I'll email you after I get off work, I could build that in if
you haven't done it yet

**Comment by meyermt** [comment]
Is this ready to merge into the master branch yet @Victoriatheeast ? I think all we need is for it to be able to start up on the ports that you specify. Then we can make smaller changes in smaller pull requests after this. But we should try to merge this if it builds and runs something.

**Comment by Victoriatheeast** [comment]
Well, it is not fully ready. I don't think you can make it run based on these, but yes we can merge it and make changes later.

**Comment by meyermt** [comment]
Do you mind if I resolve the conflicts with master branch? I will keep all your Stock class changes but I am going to delete your changes to other classes in admin server. Sound good? If so I'll merge this

**Comment by Victoriatheeast** [comment]
Sorry this one is messy, merge the other request for the tradepeer branch.

**Pull request closed without merging**
